version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
  
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Instalando dependências do projeto...
      - npm install --loglevel=error
      - echo Executando testes unitários...
      - npm test