services:
  server:
    build: .
    container_name: bia
    ports:
      - 3001:8080
    environment:
      DB_USER: postgres
      DB_PWD: MZhauW4KEwqfYSOgnDNo
      DB_HOST: bia-labs-4-2.cluster-c03m8ueqgif2.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
